### ISSUE TITLE
Button's type is submit

### ISSUE THREAD

**Issue by awsxuhi** [jasmaa/cloudscape-file-uploader#9]
Not sure if you have tested this component. I tried it and failed.

The FileUploader component is a Button with type equals to submit. When I clicked the button the choose files, it triggered "the submit" automatically. I tried to use "onFilesUploaded={(event) => {
                event.preventDefault();
                console.log("%cfile", "color: blue; font-weight: bold;", event);
              }}" in the component. However, it didn't work.

**Comment by jasmaa** [comment]
Looks like default formAction for Cloudscape Button is submit. Updating it to none.
